namespace OwnORMForm
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            MainTabControl = new TabControl();
            StudentPage = new TabPage();
            ShowStudentBtn = new Button();
            SearchStudentTextbox = new TextBox();
            DeleteStudentBtn = new Button();
            EditStudentBtn = new Button();
            CreateStudentBtn = new Button();
            StudentDataGridView = new DataGridView();
            Students_TitleLabel = new Label();
            ClassesPage = new TabPage();
            ShowClassBtn = new Button();
            SearchClassesTextBox = new TextBox();
            DeleteClassesBtn = new Button();
            EditClassesBtn = new Button();
            CreateClassBtn = new Button();
            ClassesDataGridView = new DataGridView();
            Classes_TitleLabel = new Label();
            CoursesPage = new TabPage();
            ShowCourseBtn = new Button();
            SearchCourseTextbox = new TextBox();
            DeleteCourseBtn = new Button();
            EditCourseBtn = new Button();
            CreateCourseBtn = new Button();
            CoursesDataGridView = new DataGridView();
            Courses_TitleLabel = new Label();
            GradesPage = new TabPage();
            ShowGradeBtn = new Button();
            SearchGradesTextbox = new TextBox();
            DeleteGradeBtn = new Button();
            EditGradeBtn = new Button();
            CreateGradeBtn = new Button();
            GradesDataGridView = new DataGridView();
            Grades_TitleLabel = new Label();
            TabControlImageList = new ImageList(components);
            MainTabControl.SuspendLayout();
            StudentPage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)StudentDataGridView).BeginInit();
            ClassesPage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)ClassesDataGridView).BeginInit();
            CoursesPage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)CoursesDataGridView).BeginInit();
            GradesPage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)GradesDataGridView).BeginInit();
            SuspendLayout();
            MainTabControl.Controls.Add(StudentPage);
            MainTabControl.Controls.Add(ClassesPage);
            MainTabControl.Controls.Add(CoursesPage);
            MainTabControl.Controls.Add(GradesPage);
            MainTabControl.Dock = DockStyle.Fill;
            MainTabControl.HotTrack = true;
            MainTabControl.ImageList = TabControlImageList;
            MainTabControl.ItemSize = new Size(62, 25);
            MainTabControl.Location = new Point(5, 5);
            MainTabControl.Margin = new Padding(0);
            MainTabControl.Name = "MainTabControl";
            MainTabControl.Padding = new Point(10, 5);
            MainTabControl.SelectedIndex = 0;
            MainTabControl.Size = new Size(904, 470);
            MainTabControl.TabIndex = 0;
            MainTabControl.SelectedIndexChanged += MainTabControl_SelectedIndexChanged;
            StudentPage.BackColor = Color.FromArgb(33, 33, 33);
            StudentPage.Controls.Add(ShowStudentBtn);
            StudentPage.Controls.Add(SearchStudentTextbox);
            StudentPage.Controls.Add(DeleteStudentBtn);
            StudentPage.Controls.Add(EditStudentBtn);
            StudentPage.Controls.Add(CreateStudentBtn);
            StudentPage.Controls.Add(StudentDataGridView);
            StudentPage.Controls.Add(Students_TitleLabel);
            StudentPage.ForeColor = Color.Gainsboro;
            StudentPage.ImageIndex = 0;
            StudentPage.Location = new Point(4, 29);
            StudentPage.Margin = new Padding(0);
            StudentPage.Name = "StudentPage";
            StudentPage.Padding = new Padding(5);
            StudentPage.Size = new Size(896, 437);
            StudentPage.TabIndex = 0;
            StudentPage.Text = "Elever";
            ShowStudentBtn.BackColor = Color.Teal;
            ShowStudentBtn.Cursor = Cursors.Hand;
            ShowStudentBtn.Enabled = false;
            ShowStudentBtn.FlatAppearance.BorderColor = Color.White;
            ShowStudentBtn.FlatStyle = FlatStyle.Flat;
            ShowStudentBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            ShowStudentBtn.Location = new Point(156, 51);
            ShowStudentBtn.Margin = new Padding(0, 0, 5, 5);
            ShowStudentBtn.Name = "ShowStudentBtn";
            ShowStudentBtn.Size = new Size(112, 33);
            ShowStudentBtn.TabIndex = 6;
            ShowStudentBtn.Text = "Vis Elev";
            ShowStudentBtn.UseVisualStyleBackColor = false;
            SearchStudentTextbox.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            SearchStudentTextbox.BackColor = Color.WhiteSmoke;
            SearchStudentTextbox.BorderStyle = BorderStyle.FixedSingle;
            SearchStudentTextbox.Font = new Font("Verdana", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            SearchStudentTextbox.Location = new Point(575, 55);
            SearchStudentTextbox.Margin = new Padding(0, 0, 0, 5);
            SearchStudentTextbox.Name = "SearchStudentTextbox";
            SearchStudentTextbox.PlaceholderText = "Søg Efter Elev";
            SearchStudentTextbox.Size = new Size(316, 27);
            SearchStudentTextbox.TabIndex = 5;
            SearchStudentTextbox.TextAlign = HorizontalAlignment.Center;
            DeleteStudentBtn.BackColor = Color.Firebrick;
            DeleteStudentBtn.Cursor = Cursors.Hand;
            DeleteStudentBtn.Enabled = false;
            DeleteStudentBtn.FlatAppearance.BorderColor = Color.White;
            DeleteStudentBtn.FlatStyle = FlatStyle.Flat;
            DeleteStudentBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            DeleteStudentBtn.Location = new Point(424, 51);
            DeleteStudentBtn.Margin = new Padding(0, 0, 5, 5);
            DeleteStudentBtn.Name = "DeleteStudentBtn";
            DeleteStudentBtn.Size = new Size(146, 33);
            DeleteStudentBtn.TabIndex = 4;
            DeleteStudentBtn.Text = "Slet Elev";
            DeleteStudentBtn.UseVisualStyleBackColor = false;
            EditStudentBtn.BackColor = Color.MediumBlue;
            EditStudentBtn.Cursor = Cursors.Hand;
            EditStudentBtn.Enabled = false;
            EditStudentBtn.FlatAppearance.BorderColor = Color.White;
            EditStudentBtn.FlatStyle = FlatStyle.Flat;
            EditStudentBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            EditStudentBtn.Location = new Point(273, 51);
            EditStudentBtn.Margin = new Padding(0, 0, 5, 5);
            EditStudentBtn.Name = "EditStudentBtn";
            EditStudentBtn.Size = new Size(146, 33);
            EditStudentBtn.TabIndex = 3;
            EditStudentBtn.Text = "Rediger Elev";
            EditStudentBtn.UseVisualStyleBackColor = false;
            CreateStudentBtn.BackColor = Color.Green;
            CreateStudentBtn.Cursor = Cursors.Hand;
            CreateStudentBtn.FlatAppearance.BorderColor = Color.White;
            CreateStudentBtn.FlatStyle = FlatStyle.Flat;
            CreateStudentBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            CreateStudentBtn.Location = new Point(5, 51);
            CreateStudentBtn.Margin = new Padding(0, 0, 5, 5);
            CreateStudentBtn.Name = "CreateStudentBtn";
            CreateStudentBtn.Size = new Size(146, 33);
            CreateStudentBtn.TabIndex = 2;
            CreateStudentBtn.Text = "Opret Elev";
            CreateStudentBtn.UseVisualStyleBackColor = false;
            StudentDataGridView.AllowUserToAddRows = false;
            StudentDataGridView.AllowUserToDeleteRows = false;
            StudentDataGridView.AllowUserToOrderColumns = true;
            StudentDataGridView.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            StudentDataGridView.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            StudentDataGridView.Location = new Point(5, 89);
            StudentDataGridView.Margin = new Padding(0);
            StudentDataGridView.Name = "StudentDataGridView";
            StudentDataGridView.ReadOnly = true;
            StudentDataGridView.Size = new Size(886, 343);
            StudentDataGridView.TabIndex = 1;
            Students_TitleLabel.Font = new Font("Verdana", 15.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            Students_TitleLabel.Location = new Point(5, 5);
            Students_TitleLabel.Margin = new Padding(0, 0, 0, 5);
            Students_TitleLabel.Name = "Students_TitleLabel";
            Students_TitleLabel.Size = new Size(886, 41);
            Students_TitleLabel.TabIndex = 0;
            Students_TitleLabel.Text = "Elever";
            Students_TitleLabel.TextAlign = ContentAlignment.MiddleLeft;
            ClassesPage.BackColor = Color.FromArgb(33, 33, 33);
            ClassesPage.Controls.Add(ShowClassBtn);
            ClassesPage.Controls.Add(SearchClassesTextBox);
            ClassesPage.Controls.Add(DeleteClassesBtn);
            ClassesPage.Controls.Add(EditClassesBtn);
            ClassesPage.Controls.Add(CreateClassBtn);
            ClassesPage.Controls.Add(ClassesDataGridView);
            ClassesPage.Controls.Add(Classes_TitleLabel);
            ClassesPage.ForeColor = Color.Gainsboro;
            ClassesPage.ImageIndex = 1;
            ClassesPage.Location = new Point(4, 29);
            ClassesPage.Margin = new Padding(0);
            ClassesPage.Name = "ClassesPage";
            ClassesPage.Padding = new Padding(5);
            ClassesPage.Size = new Size(896, 437);
            ClassesPage.TabIndex = 1;
            ClassesPage.Text = "Klasser";
            ShowClassBtn.BackColor = Color.Teal;
            ShowClassBtn.Cursor = Cursors.Hand;
            ShowClassBtn.Enabled = false;
            ShowClassBtn.FlatAppearance.BorderColor = Color.White;
            ShowClassBtn.FlatStyle = FlatStyle.Flat;
            ShowClassBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            ShowClassBtn.Location = new Point(156, 51);
            ShowClassBtn.Margin = new Padding(0, 0, 5, 5);
            ShowClassBtn.Name = "ShowClassBtn";
            ShowClassBtn.Size = new Size(112, 33);
            ShowClassBtn.TabIndex = 13;
            ShowClassBtn.Text = "Vis Klasse";
            ShowClassBtn.UseVisualStyleBackColor = false;
            SearchClassesTextBox.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            SearchClassesTextBox.BackColor = Color.WhiteSmoke;
            SearchClassesTextBox.BorderStyle = BorderStyle.FixedSingle;
            SearchClassesTextBox.Font = new Font("Verdana", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            SearchClassesTextBox.Location = new Point(575, 55);
            SearchClassesTextBox.Margin = new Padding(0, 0, 0, 5);
            SearchClassesTextBox.Name = "SearchClassesTextBox";
            SearchClassesTextBox.PlaceholderText = "Søg Efter Klasse";
            SearchClassesTextBox.Size = new Size(316, 27);
            SearchClassesTextBox.TabIndex = 12;
            SearchClassesTextBox.TextAlign = HorizontalAlignment.Center;
            DeleteClassesBtn.BackColor = Color.Firebrick;
            DeleteClassesBtn.Cursor = Cursors.Hand;
            DeleteClassesBtn.Enabled = false;
            DeleteClassesBtn.FlatAppearance.BorderColor = Color.White;
            DeleteClassesBtn.FlatStyle = FlatStyle.Flat;
            DeleteClassesBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            DeleteClassesBtn.Location = new Point(424, 51);
            DeleteClassesBtn.Margin = new Padding(0, 0, 5, 5);
            DeleteClassesBtn.Name = "DeleteClassesBtn";
            DeleteClassesBtn.Size = new Size(146, 33);
            DeleteClassesBtn.TabIndex = 11;
            DeleteClassesBtn.Text = "Slet Klasse";
            DeleteClassesBtn.UseVisualStyleBackColor = false;
            EditClassesBtn.BackColor = Color.MediumBlue;
            EditClassesBtn.Cursor = Cursors.Hand;
            EditClassesBtn.Enabled = false;
            EditClassesBtn.FlatAppearance.BorderColor = Color.White;
            EditClassesBtn.FlatStyle = FlatStyle.Flat;
            EditClassesBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            EditClassesBtn.Location = new Point(273, 51);
            EditClassesBtn.Margin = new Padding(0, 0, 5, 5);
            EditClassesBtn.Name = "EditClassesBtn";
            EditClassesBtn.Size = new Size(146, 33);
            EditClassesBtn.TabIndex = 10;
            EditClassesBtn.Text = "Rediger Klasse";
            EditClassesBtn.UseVisualStyleBackColor = false;
            CreateClassBtn.BackColor = Color.Green;
            CreateClassBtn.Cursor = Cursors.Hand;
            CreateClassBtn.FlatAppearance.BorderColor = Color.White;
            CreateClassBtn.FlatStyle = FlatStyle.Flat;
            CreateClassBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            CreateClassBtn.Location = new Point(5, 51);
            CreateClassBtn.Margin = new Padding(0, 0, 5, 5);
            CreateClassBtn.Name = "CreateClassBtn";
            CreateClassBtn.Size = new Size(146, 33);
            CreateClassBtn.TabIndex = 9;
            CreateClassBtn.Text = "Opret Klasse";
            CreateClassBtn.UseVisualStyleBackColor = false;
            ClassesDataGridView.AllowUserToAddRows = false;
            ClassesDataGridView.AllowUserToDeleteRows = false;
            ClassesDataGridView.AllowUserToOrderColumns = true;
            ClassesDataGridView.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            ClassesDataGridView.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            ClassesDataGridView.Location = new Point(5, 89);
            ClassesDataGridView.Margin = new Padding(0);
            ClassesDataGridView.Name = "ClassesDataGridView";
            ClassesDataGridView.ReadOnly = true;
            ClassesDataGridView.Size = new Size(886, 343);
            ClassesDataGridView.TabIndex = 8;
            Classes_TitleLabel.Font = new Font("Verdana", 15.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            Classes_TitleLabel.Location = new Point(5, 5);
            Classes_TitleLabel.Margin = new Padding(0, 0, 0, 5);
            Classes_TitleLabel.Name = "Classes_TitleLabel";
            Classes_TitleLabel.Size = new Size(886, 41);
            Classes_TitleLabel.TabIndex = 7;
            Classes_TitleLabel.Text = "Klasser";
            Classes_TitleLabel.TextAlign = ContentAlignment.MiddleLeft;
            CoursesPage.BackColor = Color.FromArgb(33, 33, 33);
            CoursesPage.Controls.Add(ShowCourseBtn);
            CoursesPage.Controls.Add(SearchCourseTextbox);
            CoursesPage.Controls.Add(DeleteCourseBtn);
            CoursesPage.Controls.Add(EditCourseBtn);
            CoursesPage.Controls.Add(CreateCourseBtn);
            CoursesPage.Controls.Add(CoursesDataGridView);
            CoursesPage.Controls.Add(Courses_TitleLabel);
            CoursesPage.ForeColor = Color.Gainsboro;
            CoursesPage.ImageIndex = 2;
            CoursesPage.Location = new Point(4, 29);
            CoursesPage.Margin = new Padding(0);
            CoursesPage.Name = "CoursesPage";
            CoursesPage.Padding = new Padding(5);
            CoursesPage.Size = new Size(896, 437);
            CoursesPage.TabIndex = 2;
            CoursesPage.Text = "Fag";
            ShowCourseBtn.BackColor = Color.Teal;
            ShowCourseBtn.Cursor = Cursors.Hand;
            ShowCourseBtn.Enabled = false;
            ShowCourseBtn.FlatAppearance.BorderColor = Color.White;
            ShowCourseBtn.FlatStyle = FlatStyle.Flat;
            ShowCourseBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            ShowCourseBtn.Location = new Point(156, 51);
            ShowCourseBtn.Margin = new Padding(0, 0, 5, 5);
            ShowCourseBtn.Name = "ShowCourseBtn";
            ShowCourseBtn.Size = new Size(112, 33);
            ShowCourseBtn.TabIndex = 20;
            ShowCourseBtn.Text = "Vis Fag";
            ShowCourseBtn.UseVisualStyleBackColor = false;
            SearchCourseTextbox.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            SearchCourseTextbox.BackColor = Color.WhiteSmoke;
            SearchCourseTextbox.BorderStyle = BorderStyle.FixedSingle;
            SearchCourseTextbox.Font = new Font("Verdana", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            SearchCourseTextbox.Location = new Point(575, 55);
            SearchCourseTextbox.Margin = new Padding(0, 0, 0, 5);
            SearchCourseTextbox.Name = "SearchCourseTextbox";
            SearchCourseTextbox.PlaceholderText = "Søg Efter Fag";
            SearchCourseTextbox.Size = new Size(316, 27);
            SearchCourseTextbox.TabIndex = 19;
            SearchCourseTextbox.TextAlign = HorizontalAlignment.Center;
            DeleteCourseBtn.BackColor = Color.Firebrick;
            DeleteCourseBtn.Cursor = Cursors.Hand;
            DeleteCourseBtn.Enabled = false;
            DeleteCourseBtn.FlatAppearance.BorderColor = Color.White;
            DeleteCourseBtn.FlatStyle = FlatStyle.Flat;
            DeleteCourseBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            DeleteCourseBtn.Location = new Point(424, 51);
            DeleteCourseBtn.Margin = new Padding(0, 0, 5, 5);
            DeleteCourseBtn.Name = "DeleteCourseBtn";
            DeleteCourseBtn.Size = new Size(146, 33);
            DeleteCourseBtn.TabIndex = 18;
            DeleteCourseBtn.Text = "Slet Fag";
            DeleteCourseBtn.UseVisualStyleBackColor = false;
            EditCourseBtn.BackColor = Color.MediumBlue;
            EditCourseBtn.Cursor = Cursors.Hand;
            EditCourseBtn.Enabled = false;
            EditCourseBtn.FlatAppearance.BorderColor = Color.White;
            EditCourseBtn.FlatStyle = FlatStyle.Flat;
            EditCourseBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            EditCourseBtn.Location = new Point(273, 51);
            EditCourseBtn.Margin = new Padding(0, 0, 5, 5);
            EditCourseBtn.Name = "EditCourseBtn";
            EditCourseBtn.Size = new Size(146, 33);
            EditCourseBtn.TabIndex = 17;
            EditCourseBtn.Text = "Rediger Fag";
            EditCourseBtn.UseVisualStyleBackColor = false;
            CreateCourseBtn.BackColor = Color.Green;
            CreateCourseBtn.Cursor = Cursors.Hand;
            CreateCourseBtn.FlatAppearance.BorderColor = Color.White;
            CreateCourseBtn.FlatStyle = FlatStyle.Flat;
            CreateCourseBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            CreateCourseBtn.Location = new Point(5, 51);
            CreateCourseBtn.Margin = new Padding(0, 0, 5, 5);
            CreateCourseBtn.Name = "CreateCourseBtn";
            CreateCourseBtn.Size = new Size(146, 33);
            CreateCourseBtn.TabIndex = 16;
            CreateCourseBtn.Text = "Opret Fag";
            CreateCourseBtn.UseVisualStyleBackColor = false;
            CoursesDataGridView.AllowUserToAddRows = false;
            CoursesDataGridView.AllowUserToDeleteRows = false;
            CoursesDataGridView.AllowUserToOrderColumns = true;
            CoursesDataGridView.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            CoursesDataGridView.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            CoursesDataGridView.Location = new Point(5, 89);
            CoursesDataGridView.Margin = new Padding(0);
            CoursesDataGridView.Name = "CoursesDataGridView";
            CoursesDataGridView.ReadOnly = true;
            CoursesDataGridView.Size = new Size(886, 343);
            CoursesDataGridView.TabIndex = 15;
            Courses_TitleLabel.Font = new Font("Verdana", 15.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            Courses_TitleLabel.Location = new Point(5, 5);
            Courses_TitleLabel.Margin = new Padding(0, 0, 0, 5);
            Courses_TitleLabel.Name = "Courses_TitleLabel";
            Courses_TitleLabel.Size = new Size(886, 41);
            Courses_TitleLabel.TabIndex = 14;
            Courses_TitleLabel.Text = "Fag";
            Courses_TitleLabel.TextAlign = ContentAlignment.MiddleLeft;
            GradesPage.BackColor = Color.FromArgb(33, 33, 33);
            GradesPage.Controls.Add(ShowGradeBtn);
            GradesPage.Controls.Add(SearchGradesTextbox);
            GradesPage.Controls.Add(DeleteGradeBtn);
            GradesPage.Controls.Add(EditGradeBtn);
            GradesPage.Controls.Add(CreateGradeBtn);
            GradesPage.Controls.Add(GradesDataGridView);
            GradesPage.Controls.Add(Grades_TitleLabel);
            GradesPage.ForeColor = Color.Gainsboro;
            GradesPage.ImageIndex = 3;
            GradesPage.Location = new Point(4, 29);
            GradesPage.Margin = new Padding(0);
            GradesPage.Name = "GradesPage";
            GradesPage.Padding = new Padding(5);
            GradesPage.Size = new Size(896, 437);
            GradesPage.TabIndex = 3;
            GradesPage.Text = "Karaktere";
            ShowGradeBtn.BackColor = Color.Teal;
            ShowGradeBtn.Cursor = Cursors.Hand;
            ShowGradeBtn.Enabled = false;
            ShowGradeBtn.FlatAppearance.BorderColor = Color.White;
            ShowGradeBtn.FlatStyle = FlatStyle.Flat;
            ShowGradeBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            ShowGradeBtn.Location = new Point(156, 51);
            ShowGradeBtn.Margin = new Padding(0, 0, 5, 5);
            ShowGradeBtn.Name = "ShowGradeBtn";
            ShowGradeBtn.Size = new Size(112, 33);
            ShowGradeBtn.TabIndex = 27;
            ShowGradeBtn.Text = "Vis Karakter";
            ShowGradeBtn.UseVisualStyleBackColor = false;
            SearchGradesTextbox.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            SearchGradesTextbox.BackColor = Color.WhiteSmoke;
            SearchGradesTextbox.BorderStyle = BorderStyle.FixedSingle;
            SearchGradesTextbox.Font = new Font("Verdana", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            SearchGradesTextbox.Location = new Point(575, 55);
            SearchGradesTextbox.Margin = new Padding(0, 0, 0, 5);
            SearchGradesTextbox.Name = "SearchGradesTextbox";
            SearchGradesTextbox.PlaceholderText = "Søg Efter Karaktere";
            SearchGradesTextbox.Size = new Size(316, 27);
            SearchGradesTextbox.TabIndex = 26;
            SearchGradesTextbox.TextAlign = HorizontalAlignment.Center;
            DeleteGradeBtn.BackColor = Color.Firebrick;
            DeleteGradeBtn.Cursor = Cursors.Hand;
            DeleteGradeBtn.Enabled = false;
            DeleteGradeBtn.FlatAppearance.BorderColor = Color.White;
            DeleteGradeBtn.FlatStyle = FlatStyle.Flat;
            DeleteGradeBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            DeleteGradeBtn.Location = new Point(424, 51);
            DeleteGradeBtn.Margin = new Padding(0, 0, 5, 5);
            DeleteGradeBtn.Name = "DeleteGradeBtn";
            DeleteGradeBtn.Size = new Size(146, 33);
            DeleteGradeBtn.TabIndex = 25;
            DeleteGradeBtn.Text = "Slet Karakter";
            DeleteGradeBtn.UseVisualStyleBackColor = false;
            EditGradeBtn.BackColor = Color.MediumBlue;
            EditGradeBtn.Cursor = Cursors.Hand;
            EditGradeBtn.Enabled = false;
            EditGradeBtn.FlatAppearance.BorderColor = Color.White;
            EditGradeBtn.FlatStyle = FlatStyle.Flat;
            EditGradeBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            EditGradeBtn.Location = new Point(273, 51);
            EditGradeBtn.Margin = new Padding(0, 0, 5, 5);
            EditGradeBtn.Name = "EditGradeBtn";
            EditGradeBtn.Size = new Size(146, 33);
            EditGradeBtn.TabIndex = 24;
            EditGradeBtn.Text = "Rediger Karakter";
            EditGradeBtn.UseVisualStyleBackColor = false;
            CreateGradeBtn.BackColor = Color.Green;
            CreateGradeBtn.Cursor = Cursors.Hand;
            CreateGradeBtn.FlatAppearance.BorderColor = Color.White;
            CreateGradeBtn.FlatStyle = FlatStyle.Flat;
            CreateGradeBtn.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            CreateGradeBtn.Location = new Point(5, 51);
            CreateGradeBtn.Margin = new Padding(0, 0, 5, 5);
            CreateGradeBtn.Name = "CreateGradeBtn";
            CreateGradeBtn.Size = new Size(146, 33);
            CreateGradeBtn.TabIndex = 23;
            CreateGradeBtn.Text = "Opret Karakter";
            CreateGradeBtn.UseVisualStyleBackColor = false;
            GradesDataGridView.AllowUserToAddRows = false;
            GradesDataGridView.AllowUserToDeleteRows = false;
            GradesDataGridView.AllowUserToOrderColumns = true;
            GradesDataGridView.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            GradesDataGridView.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            GradesDataGridView.Location = new Point(5, 89);
            GradesDataGridView.Margin = new Padding(0);
            GradesDataGridView.Name = "GradesDataGridView";
            GradesDataGridView.ReadOnly = true;
            GradesDataGridView.Size = new Size(886, 343);
            GradesDataGridView.TabIndex = 22;
            Grades_TitleLabel.Font = new Font("Verdana", 15.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            Grades_TitleLabel.Location = new Point(5, 5);
            Grades_TitleLabel.Margin = new Padding(0, 0, 0, 5);
            Grades_TitleLabel.Name = "Grades_TitleLabel";
            Grades_TitleLabel.Size = new Size(886, 41);
            Grades_TitleLabel.TabIndex = 21;
            Grades_TitleLabel.Text = "Karaktere";
            Grades_TitleLabel.TextAlign = ContentAlignment.MiddleLeft;
            TabControlImageList.ColorDepth = ColorDepth.Depth32Bit;
            TabControlImageList.ImageStream = (ImageListStreamer)resources.GetObject("TabControlImageList.ImageStream");
            TabControlImageList.TransparentColor = Color.Transparent;
            TabControlImageList.Images.SetKeyName(0, "Graphicloads-100-Flat-Student.48.png");
            TabControlImageList.Images.SetKeyName(1, "Class.png");
            TabControlImageList.Images.SetKeyName(2, "E-Learning.png");
            TabControlImageList.Images.SetKeyName(3, "Report Card.png");
            AutoScaleDimensions = new SizeF(8F, 16F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(33, 33, 33);
            ClientSize = new Size(914, 480);
            Controls.Add(MainTabControl);
            Font = new Font("Verdana", 9.75F, FontStyle.Regular, GraphicsUnit.Point, 0);
            Icon = (Icon)resources.GetObject("$this.Icon");
            Name = "MainForm";
            Padding = new Padding(5);
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Own ORM";
            Shown += MainForm_Shown;
            MainTabControl.ResumeLayout(false);
            StudentPage.ResumeLayout(false);
            StudentPage.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)StudentDataGridView).EndInit();
            ClassesPage.ResumeLayout(false);
            ClassesPage.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)ClassesDataGridView).EndInit();
            CoursesPage.ResumeLayout(false);
            CoursesPage.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)CoursesDataGridView).EndInit();
            GradesPage.ResumeLayout(false);
            GradesPage.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)GradesDataGridView).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private TabControl MainTabControl;
        private TabPage StudentPage;
        private TabPage ClassesPage;
        private TabPage CoursesPage;
        private TabPage GradesPage;
        private ImageList TabControlImageList;
        private Label Students_TitleLabel;
        private Button CreateStudentBtn;
        private DataGridView StudentDataGridView;
        private Button EditStudentBtn;
        private Button DeleteStudentBtn;
        private TextBox SearchStudentTextbox;
        private Button ShowStudentBtn;
        private Button ShowClassBtn;
        private TextBox SearchClassesTextBox;
        private Button DeleteClassesBtn;
        private Button EditClassesBtn;
        private Button CreateClassBtn;
        private DataGridView ClassesDataGridView;
        private Label Classes_TitleLabel;
        private Button ShowCourseBtn;
        private TextBox SearchCourseTextbox;
        private Button DeleteCourseBtn;
        private Button EditCourseBtn;
        private Button CreateCourseBtn;
        private DataGridView CoursesDataGridView;
        private Label Courses_TitleLabel;
        private Button ShowGradeBtn;
        private TextBox SearchGradesTextbox;
        private Button DeleteGradeBtn;
        private Button EditGradeBtn;
        private Button CreateGradeBtn;
        private DataGridView GradesDataGridView;
        private Label Grades_TitleLabel;
    }
}
